### ISSUE TITLE
Tab characters in query result in validationErrorType=FieldUndefined

### ISSUE THREAD

**Issue by marstein** [graphql/graphiql#120] opened 2016-04-12 23:56 UTC
If there is a \t tab character in the query pane, an error results.

`"[ValidationError{validationErrorType=FieldUndefined, sourceLocations=[SourceLocation{line=1, column=111}], description='Field t is undefined'}]"`

Field t is the \t tab character. The spec says that tab characters are parsed as whitespace.

**Comment by asiandrummer** [comment] 2016-04-28 17:00
Hi @marstein - do you mean a literal `\t` string? Could you share the query you're having this problem with?
When I read the spec I automatically assumed tab characters meant the whitespaces caused from pressing/typing the tab character, not `\t` string. cc @leebyron since I might be missing something.

**Comment by wincent** [comment] 2016-12-10 01:00
Doing a bit of spring cleaning of issues that haven't been touched in a while.

Not able to reproduce this with a literal tab (it's whitespace) or `\t` (it's a syntax error), leaving only `t`, which reports a (presumably back-end-specific) error with message `Cannot query field "t" on type "..."`, so going to need some more repro information. Marking as closed for now, but feel free to comment with more info and we can re-open.

**Closed by wincent** 2016-12-10 01:00 UTC
