### ISSUE TITLE
editor is broken when used in create-react-app

### ISSUE THREAD

**Issue by helios1138** [graphql/graphiql#599] opened 2017-09-19 11:13 UTC
I'm trying to embed the GraphiQL inside existing app. Whole thing looks styled correctly, but the query editor section itself is not responding at all: it's gray, there's no cursor, no content and it doesn't react to input.

I've tried `import 'graphiql/graphiql.css'`, tried using `react-helmet` to put a  style `<link>` dynamically, manually doing stuff like `document.head.insertBefore()` in wrapper's `componentDidMount()` - nothing works.

It does work, however, if I put CDN link to `graphiql.css` directly to `public/index.html` which seems like a hack right now

**Comment by asiandrummer** [comment] 2017-09-27 23:07
@helios1138 I think this is because the css file needs to be loaded before GraphiQL component becomes mounted - how did you try embedding GraphiQL without including the stylesheet in `index.html`? I'd say loading a GraphiQL stylesheet before running rendering JavaScript code would be the recommended way, but am curious how you did it initially.

**Comment by helios1138** [comment] 2017-09-28 11:20
@asiandrummer well, my goal was to embed the GraphiQL into an existing app (I'm using `create-react-app`), so I created a simple wrapper component like this
```jsx
import 'graphiql/graphiql.css' // this was supposed to work, currently removed
                               // and styles instead are loaded in index.html from CDN

import React from 'react'
import { connect } from 'react-redux'
import GraphiQL from 'graphiql'
import fetch from 'isomorphic-fetch'

@connect(state => ({ token: state.auth.token }))
export class GraphiQLWrapper extends React.Component {
  request = async params => {
    const response = await fetch(`${process.env.REACT_APP_API_URL}/graphql`, {
      method: 'post',
      headers: {
        'Content-Type': 'application/json',
        'Token': this.props.token
      },
      body: JSON.stringify(params),
    })

    return response.json()
  }

  render () {
    return <GraphiQL fetcher={this.request} />
  }
}
```

**Comment by asiandrummer** [comment] 2017-09-28 17:56
Also, from #462 someone also had this issue until the parent div's height was set to 100%:
```
.App {
  height: 100vh;
}
```
Would this fix the issue?

**Comment by helios1138** [comment] 2017-09-29 20:40
no, in my case all the parents of the wrapper already had 100% height

**Comment by hassankhan** [comment] 2017-12-13 20:48
+1 running into the same issue, thought it was something I was doing wrong.

**Comment by sbrigham** [comment] 2018-01-21 18:49
I changed the container the react was mounting to from a div to a span and it fixed my css issues. It looks like there is an issue when .graphql-container is surrounded by a container that is display: block.

**Comment by enricribas** [comment] 2018-03-08 14:36
This still appears broken, it used to work for me and then one day, the css menus stopped working 

![image](https://user-images.githubusercontent.com/438493/37156420-0d06f784-22b4-11e8-9d7f-d58196db1ee1.png)

It still works for some people at my company but not for others. 
The open class is added to elements when clicked, but nothing opens.

**Comment by RavinderSinghMaan** [comment] 2019-04-13 23:54
This issue still seems to be there. It works if I include link to CDN as suggested by @helios1138 but was wondering if there is better way to do it?

**Comment by acao** [comment] 2019-06-25 02:41
@enricribas that appears to be a customized instance of graphiql, the form for editing headers is not part of this codebase

this is a very real bug, and I've seen it in some cases. there could be numerous issues, but I think #770 might be a duplicate of some of these cases. for anyone still having this issue, please try running a simple command in your browser console:
```g.refresh()```
the GraphiQL component attaches `window.g = this` on componentDidMount and GraphiQL component has a method called `refresh()` that invokes `CodeMirror.editor.refresh()` on all of the editors.

if this fixes anyone's rendering issues, then it confirms that you might actually be seeing a race condition on loading of Codemirror modules, as described in #770 in more detail.

**Comment by johncrisostomo** [comment] 2021-01-28 05:10
I tried to do what OP was doing and ran into the same issue

**Comment by acao** [comment] 2021-01-28 15:15
we have a `create-react-app` example now that works fine.

> @helios1138 I think this is because the css file needs to be loaded before GraphiQL component becomes mounted - how did you try embedding GraphiQL without including the stylesheet in `index.html`? I'd say loading a GraphiQL stylesheet before running rendering JavaScript code would be the recommended way, but am curious how you did it initially.

if you end up coming across this issue, it's probably because of this, or because you just need to style the css properly. please see our examples or the `graphiql/packages/readme`

**Closed by acao** 2021-01-28 15:15 UTC
Labels: needs info, question
