### ISSUE TITLE
"shift+space" should type a space character instead of popping up autocomplete

### ISSUE THREAD

**Issue by benkuhn** [graphql/graphiql#678] opened 2018-05-10 15:31 UTC
Hey, thanks for making a super awesome tool! Sorry to nitpick it :)

Steps to reproduce on OS X 10.13.5, Chrome 66.0.3359.139:

- Go to https://developer.github.com/v4/explorer/
- Position the cursor just after the first curly brace
- Hold down "shift"
- Hit the space bar

Expected behavior: a space character appears (as in e.g. Github issue composer, VS Code, WebStorm, system default text fields, etc.)

Actual behavior: autocomplete box pops up and no space appears.

Explanation: When typing strings like `a: "b"` I'm in the habit of holding down the shift key while typing the space instead of pressing it twice. Even when typing something like `a: 1` I often hold down Shift a little bit too long. It's not too bad, but it's a little distracting.

**Comment by hamzah-bao** [comment] 2020-02-12 09:51
I agree it would be great to have this, particularly for defining the types of each variable.

**Comment by joshuagoran** [comment] 2020-02-18 21:41
agreed! I find it very awkward to be unable to type : " () {} and other characters that require the shift key while having to deliberately lift from the shift key to type an adjacent space character

**Comment by acao** [comment] 2021-01-28 18:24
ah, this is awkward because some users have come to expect it, but I can see how this would be annoying. because it's implemented here in 1.0:

https://github.com/graphql/graphiql/blob/881d8b5e2ed0e785002a04b67965f1e35cc65e73/packages/graphiql/src/components/QueryEditor.tsx#L145

for 1.4.0 we will be allowing users to disable or override keybindings #795.  for this to happen, you would just need to pass the prop `extraKeys={{'Shift-Space': false }}`or maybe `disableKeys={["Shift-Space"]}` to make it simpler to just disable keybindings. in this case, shift+space would lead to a space because there is no key combination for that.

in 2.0.0 we will have entirely different keybindings because we will be using monaco-graphql, for many reasons, but especially because codemirror isn't usable by screenreaders. hopefully in 2 we can manage to squeeze in an API and user-level UI for configuring keyboard shortcuts, even.

I will close and mark this as a duplicate of #795 for that reason

**Closed by acao** 2021-01-28 18:24 UTC
