### ISSUE TITLE
[graphiql] setup turbo

### ISSUE THREAD

**Issue by B2o5T** [graphql/graphiql#3058] opened 2023-02-27 12:58 UTC
current `build` command takes time for rebuilding when some packages were not changed, setup turbo will boost build time

**Comment by acao** [comment] 2023-03-04 13:27
@B2o5T I am already restructing the `build` command for the`pnpm` effort. please hold off, as the issue is we have diverged from typescript project references. turbo will not speed this up

**Comment by acao** [comment] 2023-03-04 13:30
closing for #2639

**Closed by acao** 2023-03-04 13:30 UTC
Labels: enhancement
