### ISSUE TITLE
[lsp-server] SyntaxError: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead.

### ISSUE THREAD

**Issue by icetomcat** [graphql/graphiql#2770] opened 2022-09-20 18:19 UTC
## Description

Decorators break graphql-language-service
If I use `export @dec class`, then typescript and eslint in my project produce the error `Declaration or statement expected.`

**Example**

```typescript
const decorator: ClassDecorator = target => target

@decorator
export class Test {}
```

**Log**

```
21.09.2022, 00:58:56 [1] (pid: 579626) graphql-language-service-usage-logs: Could not parse the TypeScript file at file:///... to extract the graphql tags:
21.09.2022, 00:58:56 [1] (pid: 579626) graphql-language-service-usage-logs: SyntaxError: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead. (15:0)
```

**Comment by yoshiakis** [comment] 2022-10-01 06:58
seems the title of this issue is an error message you've got. Please describe how you've got that.

**Comment by acao** [comment] 2022-10-03 08:00
This is a duplicate related to enabling legacy decorators

**Comment by yoshiakis** [comment] 2022-10-07 23:40
Hey @acao , thanks your explanation!  Is this a duplicate of #2294 ?

**Comment by acao** [comment] 2022-10-15 16:24
@yoshiakis indeed! Thank you, closing for this ticket with more information

**Closed by acao** 2022-10-15 16:24 UTC
Labels: needs info
