### ISSUE TITLE
Refresh browser can't execute request without make a change

### ISSUE THREAD

**Issue by rohmanhm** [graphql/graphiql#248] opened 2016-12-12 03:56 UTC
When I go to `http://localhost:3001/graphql?query=%7B%0A%20%20people(id%3A%2011)%7B%0A%20%20%20%20id%0A%20%20%20%20firstName%0A%20%20%20%20lastName%0A%20%20%20%20email%0A%20%20%7D%0A%7D&operationName=null` I can't directly run my request when DOM is ready.

Showing this
```
{
  "errors": [
    {
      "message": "Unknown operation named \"null\"."
    }
  ]
}
```

I must change little bit, like add some space and it works again like normally.

**Comment by asiandrummer** [comment] 2016-12-12 05:38
Hi @rohmanhm - I see your url includes `operationName=null`; is there a specific reason why you're setting it as that? Could you remove that parameter and try the updated URL again?

**Comment by rohmanhm** [comment] 2016-12-12 08:04
yeah, I removed and work perfectly like i want.
But the problem is

**Comment by asiandrummer** [comment] 2016-12-12 21:08
I'm not sure how you got that URL - I tested with [the SWAPI example](http://graphql-swapi.parseapp.com/) and wasn't able to reproduce the issue. How did you get the URL? It's possible there's a bug with how we save the query on the address bar.

Closing this issue since it's resolved - feel free to continue this conversation here, or we could open another issue that tackles other problems :D

**Closed by asiandrummer** 2016-12-12 21:08 UTC
Labels: question

**Comment by yuricamara** [comment] 2017-07-14 16:22
I have exactly the same issue here! Everything as both of you related.

This is happing while I follow [How To GraphQL -The Fullstack Tutorial for GraphQL ](https://www.howtographql.com/graphql-js/7-using-data-loaders/)

>   "dependencies": {
    "body-parser": "^1.17.2",
    "dataloader": "^1.3.0",
    "express": "^4.15.3",
    "graphql": "^0.10.3",
    "graphql-server-express": "^1.0.0",
    "graphql-tools": "^1.1.0",
    "mongodb": "^2.2.30"
  },

**Comment by asiandrummer** [comment] 2017-07-14 21:10
@yuricamara This issue is resolved with the recent publish for `express-graphql` and `graphiql`, and I'm assuming either `graphql-server-express` or `graphql-tools` is using the older version of `express-graphql` or `graphiql`. @helfer might be able to assist you furthermore.

**Comment by yuricamara** [comment] 2017-07-16 14:47
Ok. Thank you!
