### ISSUE TITLE
"message": "Unknown operation named \"undefined\"."

### ISSUE THREAD

**Issue by shongololo** [graphql/graphiql#234] opened 2016-12-06 20:48 UTC
I'm testing / debugging resolvers using GraphiQL. At times, seemingly prompted by restarting the backend app, I'll start getting responses like this:

```
{
  "errors": [
    {
      "message": "Unknown operation named \"undefined\"."
    }
  ]
}
```
Restarting the app or refreshing the GraphiQL page do not fix the error. However, cutting the query and pasting it back into the query window seems to resolve the issue.

Thanks.

**Comment by wincent** [comment] 2016-12-09 19:16
Thanks for submitting the report, @shongololo. However, I think we might need a more concrete repro recipe. I know this might be hard, if the issue is intermittent; do you see it on every backend restart? Can you provide a little more detail about what versions you are running and how?

**Comment by jinxac** [comment] 2016-12-18 22:23
Even i facing this issue while calling mutations on my sample project. 

Sharing few details :- 

**Mutation Query**

```
mutation{
 toggleTodo(input:{
  id:"0"
}){
  todo{
    id
  }
}
}
```

**Schema.js**

```
const GraphQLChangeTodoStatusMutation = mutationWithClientMutationId({
  name : 'ToggleTodoStatus',
  description : 'Toggle status of todo',
  inputFields : {
    id: { type: new GraphQLNonNull(GraphQLID) },
  },
   outputFields: {
     todo: {
      type: todoType,
      resolve: ({localTodoId}) => getTodo(localTodoId),
    },
  },
  mutateAndGetPayload: ({id}) => {
   const localTodoId = fromGlobalId(id).id;
   toggleTodo(localTodoId);
   return {localTodoId};
 },
})

const Mutation = new GraphQLObjectType({
  name: 'Mutation',
  fields : {
    toggleTodo: GraphQLChangeTodoStatusMutation
  }
})

const Schema = new GraphQLSchema({
  query  : queryType,
  mutation : Mutation
})
```

**Mock data**

```
class Todo {}

let nextTodoId = 0

const todosById = []

addTodo('First task',false)
addTodo('Second task',false)

function addTodo(text,complete){
  const todo = new Todo()
  todo.complete = complete
  todo.id = `${nextTodoId++}`;
  todo.text = text;
  todosById.push(todo)
  return todo.id
}

function getTodos(){
  return todosById
}

function getTodo(id){
  return todosById[id]
}

function toggleTodo(id){
    todosById.map(function(todo,index){
    if(todo.id === id ){
    todo.complete = !todo.complete
    }
  })
}

module.exports = {
  Todo,
  addTodo,
  getTodos,
  toggleTodo
}

```

**Comment by asiandrummer** [comment] 2016-12-20 07:55
This happens when `GraphiQL` is trying to figure out which operation under the `operationName` it wants to run, as the query editor supports having multiple query contexts and running each query by specifying which one.

Are there some steps we can follow to reproduce the issue?

**Comment by leebyron** [comment] 2017-01-10 00:17
I'm not exactly sure what the root issue is, but I think this is due to saving state between runs. localStorage coerces everything to a String before saving it, so setting `undefined` results in getting `"undefined"`.

**Comment by kastermester** [comment] 2017-06-21 16:04
I still hit this issue when using unnamed queries/mutations/subscriptions. The issue arises when entering a query, like:

```graphql
mutation {
  someMutation(input: {
    clientMutationId: ""
  }) {
    clientMutationId
  }
}
```

If one enters this query, and executes it - everything works as intended. From here, a second reload will yield the error. If doing the exact same query but naming the operation, like this:
```graphql
mutation MyMutation {
  someMutation(input: {
    clientMutationId: ""
  }) {
    clientMutationId
  }
}
```

Then no error occours.

**Comment by mairatma** [comment] 2017-06-29 21:10
Just confirming that I'm having the same problem @kastermester mentioned here. It's pretty annoying and really easy to reproduce, you just need to: run a unnamed mutation, refresh the page and run it again. I'm using the graphiql that [graphql-server-express](https://www.npmjs.com/package/graphql-server-express) renders, which seems to be at [0.10.2](https://github.com/apollographql/graphql-server/blob/master/packages/graphql-server-module-graphiql/src/renderGraphiQL.ts#L32).

**Comment by mike-marcacci** [comment] 2017-06-30 17:08
I run into this from time to time as well. @leebyron is definitely correct that the string `"undefined"` is getting serialized in both localStorage and the search params:

![screenshot](https://user-images.githubusercontent.com/690517/27746364-2f76dcb2-5d84-11e7-9705-58d9ba8d2582.png)


My suspicion is that the latter (the search param) is the real culprit here, as simply deleting it resolves the issue, even though `undefined` remains in localStorage.

**Comment by Durisvk** [comment] 2017-07-06 20:24
I have the same problem, how long would it take to fix this on your side? Are you working on it?

**Comment by asiandrummer** [comment] 2017-07-07 01:44
This is weird - after [v0.10.0 release](https://github.com/graphql/graphiql/releases/tag/v0.10.0) that includes the fix for the race condition in updating `operationName` and the `queryFacts` fix, this issue should have gone away. Basically I don't understand how (and cannot reproduce) the query without `operationName` can update the URL with "&operationName=undefined" - [this code in example/index.html](https://github.com/graphql/graphiql/blob/master/example/index.html#L98) should guard from such a case.

I can reproduce this issue when I explicitly put `&operationName=undefined` in the address bar. I can put in a preventive fix not to update the URL when `operationName === null`, but it feels wrong since either I'm missing something here or something funky is going on.

@Durisvk @mairatma @kastermester Were you guys able to repro this issue from the example app in GraphiQL? Is there a different setup for you guys?

**Comment by IvanGoncharov** [comment] 2017-07-07 09:13
>  this code in example/index.html should guard from such a case.

@asiandrummer You need to propagate this change to `express-graphql` and other servers.
For example, see this: https://github.com/graphql/express-graphql/blob/master/src/renderGraphiQL.js#L86-L89

**Comment by mairatma** [comment] 2017-07-07 12:59
Just confirming that in my case this happens through `express-graphql` as well. Maybe it's just a matter of updating something there.

**Comment by asiandrummer** [comment] 2017-07-07 19:25
Got it - closing this issue here, opening/fixing in `express-graphql`. Thanks everyone.

**Closed by asiandrummer** 2017-07-07 19:25 UTC
Labels: bug, help wanted, needs info

**Comment by Durisvk** [comment] 2017-07-07 20:13
I have the same issue here and I am not using `express-graphql`... I use `hapi` server and `apollo-server` for graphql...

**Comment by asiandrummer** [comment] 2017-07-07 20:18
@Durisvk Doesn't `apollo-server` use `express-graphql` to expose GraphiQL (asking since I haven't tried using `apollo-server`)

**Comment by Durisvk** [comment] 2017-07-07 22:15
@asiandrummer That's the implementation detail I didn't study so I don't know, but I think they are using `Hapi` for GraphiQL since I am registering it as a plugin for `Hapi` like this:

```
server.register([{
        register: apolloHapi,
            options: {
                path: '/graphql',
                apolloOptions: (req) => {
                    const identity = options.safeGuard.authenticate(req);
                    return {
                        context: { identity },
                        pretty: true,
                        schema: graphqlConfig(options).executableSchema,
                    };
                },
            },
        },
        {
            register: graphiqlHapi,
            options: {
                path: '/graphiql',
                graphiqlOptions: {
                    endpointURL: '/graphql',
                },
            },
        },
    ]);
```

**Comment by asiandrummer** [comment] 2017-07-08 00:02
@Durisvk `apollo-graphql` doesn't use `express-graphql`, but it copies [how GraphiQL can be rendered as a module](https://github.com/apollographql/graphql-server/blob/master/packages/graphql-server-module-graphiql/src/renderGraphiQL.ts).

**Comment by apoberez** [comment] 2018-02-08 21:14
Hello, same issue using this tutorial http://docs.graphene-python.org/projects/sqlalchemy/en/latest/tutorial/

**Comment by muke5hy** [comment] 2018-11-04 18:17
@apoberez Any solution you found? I'm facing the same issue while following tutorial at http://docs.graphene-python.org/projects/django/en/latest/tutorial-plain/#getting-relations

**Comment by defiler** [comment] 2018-11-27 14:00
Just hitting F5 reproduces this error.
For now, workaround is Ctrl+A, Ctrl+X, Ctrl+V and query runs normal.

**Comment by defiler** [comment] 2018-11-27 14:18
For **graphene-python** users who can afford **monkey-patching the python lib** for development process, there is a simple solution:
in the file _graphql/execution/utils.py_ at the beginning of _init_ func of a class _ExecutionContext_ you can paste something like
```
if operation_name == 'undefined':
    operation_name = None
```

**Comment by Hubro** [comment] 2020-02-16 17:32
This is happening to me too. Indeed, cutting and pasting the query fixes it! I'm using graphene-python with flask-graphql. GraphiQL is built in to flask-graphql.

**Comment by acao** [comment] 2020-02-16 18:35
seems your implementation might be running an outdated version of GraphiQL. can you confirm which version you are using? Do you have any more information about your particular implementation?

**Comment by Hubro** [comment] 2020-02-16 18:39
I am using `Flask-GraphQL==2.0.1`. By [the source](https://github.com/graphql-python/flask-graphql/blob/v2.0.1/flask_graphql/render_graphiql.py) it seems they embed GraphiQL version 0.11.11.

**Comment by acao** [comment] 2020-02-16 18:42
@Hubro ah ok I see, yeah it's lockewd. I can open a PR to upgrade and improve the implementation a bit, but that would be up to the maintianer, unless pip allows you to install from my fork. I'd love to make sure flask users have an up-to-date implementation!

**Comment by Hubro** [comment] 2020-02-16 18:44
@acao I just opened an issue about it now... :P

https://github.com/graphql-python/flask-graphql/issues/75

A pull request would be neat!
