### ISSUE TITLE
Regression from 1.9.0 to 1.9.1 of graphql-language-service-parser - "Unexpected token: punc (.)"

### ISSUE THREAD

**Issue by floyd-may** [graphql/graphiql#1833] opened 2021-04-13 17:25 UTC
My builds recently began failing due to the following error:
```
🚨  /root/project/src/frontend/node_modules/graphql-language-service-parser/esm/onlineParser.js: Unexpected token: punc (.)
    at Z.get (/root/project/src/frontend/node_modules/terser/dist/bundle.min.js:1:525)
    at Object.errorToJson (/root/project/src/frontend/node_modules/@parcel/utils/src/errorUtils.js:9:20)
    at Pipeline.process (/root/project/src/frontend/node_modules/parcel-bundler/src/Pipeline.js:29:26)
    at async Object.run (/root/project/src/frontend/node_modules/parcel-bundler/src/worker.js:15:12)
    at async Child.handleRequest (/root/project/src/frontend/node_modules/@parcel/workers/src/child.js:60:26)
```

Noticing `graphql-language-service-parser` at the top of the call stack, I checked the installed version (1.9.1). I then pinned it to 1.9.0, and the error went away. There's some kind of regression here that happened from 1.9.0 to 1.9.1. Pinning for now gets me past this, but wanted to report so you all could look into it.

Thanks!

### Update

I also had to pin `graphql-language-service-interface` to 2.8.2 due to a similar error:

```
🚨  /root/project/src/frontend/node_modules/graphql-language-service-interface/esm/getAutocompleteSuggestions.js: Unexpected token: punc (.)
    at Z.get (/root/project/src/frontend/node_modules/terser/dist/bundle.min.js:1:525)
    at Object.errorToJson (/root/project/src/frontend/node_modules/@parcel/utils/src/errorUtils.js:9:20)
    at Pipeline.process (/root/project/src/frontend/node_modules/parcel-bundler/src/Pipeline.js:29:26)
    at async Object.run (/root/project/src/frontend/node_modules/parcel-bundler/src/worker.js:15:12)
    at async Child.handleRequest (/root/project/src/frontend/node_modules/@parcel/workers/src/child.js:60:26)
```

**Comment by liadb** [comment] 2021-04-18 08:17
Thanks!
This worked for me (package.json):

```json
"resolutions": {
    "graphql-language-service-parser": "1.9.0",
    "graphql-language-service-interface": "2.8.2"
  }
```

**Comment by acao** [comment] 2021-04-18 09:41
Yes I got this error as well. For some reason it isn’t transpiling the optional chaining as we prescribed. Hopefully can get to this in the coming weeks

**Comment by acao** [comment] 2021-04-18 23:41
marking this a duplicate of #1832

**Closed by acao** 2021-04-18 23:41 UTC
