### ISSUE TITLE
[graphiql] Tab duplicating when using only `shouldPersistHeaders`. 

### ISSUE THREAD

**Issue by tcK1** [graphql/graphiql#3107] opened 2023-03-20 14:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When refreshing (F5 or cmd/ctrl+r) the page, sometimes the current tab is duplicated without the persisted headers.

### Expected Behavior

It should not duplicate the tab.

### Steps To Reproduce

```Markdown
Comment all these props besides `shouldPersistHeaders: true,`.

https://github.com/graphql/graphiql/blob/9d9478aea7536d2957e4371cef4f30577db2113d/packages/graphiql/resources/renderExample.js#L99-L110

This is also easily reproduced in the wild using the CDN example and setting the `shouldPersistHeaders: true` prop.
```

### Module pattern

- [ ] graphiql-umd
- [ ] graphiql-esm
- [ ] graphiql-commonjs

### Environment

```Markdown
- GraphiQL Version: master
- OS: MacOS
- Browser: chrome
```

**Comment by acao** [comment] 2023-07-16 10:35
closing as duplicate of #2825

**Closed by acao** 2023-07-16 10:35 UTC
Labels: bug, graphiql
