### ISSUE TITLE
Headers are not sent with the request

### ISSUE THREAD

**Issue by Efesto** [graphql/graphiql#2707] opened 2022-08-26 09:37 UTC
I was testing Graphiql 2 on https://graphql.org/swapi-graphql and I've noticed that the headers values are not sent with the request

![Screenshot 2022-08-26 at 11 37 05](https://user-images.githubusercontent.com/2961753/186875527-8919b5ae-dec9-4c37-a37b-7a3728c5da1a.png)

I've reset my local storage but the issue persists

Apologies if this has already been reported

**Comment by acao** [comment] 2022-08-26 11:16
No worries, it was re-opened just after you opened this! #2380

**Comment by thomasheyenbrock** [comment] 2022-08-26 13:01
Thanks for reporting! Looking into this 👀

**Comment by thomasheyenbrock** [comment] 2022-08-26 13:54
This is a problem with the fetcher function that is used for this example page, not a bug in GraphiQL. The headers are picked up correctly but the fetcher function does not include them on the request.

**Comment by thomasheyenbrock** [comment] 2022-08-26 14:20
Should be fixed by https://github.com/graphql/swapi-graphql/pull/211

**Comment by acao** [comment] 2022-08-26 15:20
for future reference, this bug would be caused by a fetcher implementation like this:

https://github.com/graphql/swapi-graphql/pull/211/files#diff-c2cc24bc9001b11b6add48a4cd8f893d5d6c6e4d1bd254158bd14ab997f552cdL83

which doesn't handle the second param, which is `headers` as they are defined statically in props

**Closed** 2022-08-26 15:20 UTC
