### ISSUE TITLE
[graphiql] v.3.0.3 list items in search results not actionable

### ISSUE THREAD

**Issue by jahglow** [graphql/graphiql#3362] opened 2023-07-20 13:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When searching schema, search result items aren't clickable. on click the result list disappears, box doesn't contract but crops the search string. No redirect happens

This behavior is only in 3.0.x, whereas 2.4.7 works well as expected alright

### Expected Behavior

Clicking a searc result should display the entity in the sidebar (as in v2.4.7)

### Steps To Reproduce

```ts
import GraphiQL from "graphiql";
// ...

export default function App (){
const fetcher = useMemo(
    () =>
      credentials
        ? buildFetcher(
            credentials.endpoint,
            credentials.login,
            credentials.password
          )
        : null,
    [credentials]
  );
  
  return fetcher && <GraphiQL fetcher={fetcher} />
  }
  ```
  ```ts
  import { getToken } from "./getToken";

export const buildFetcher = (
  endpoint: string,
  login: string,
  password: string
) => async (params: unknown) => {
  const token = await getToken(endpoint, login, password);

  return fetch(`${endpoint}/graphql`, {
    method: "post",
    headers: {
      "Content-Type": "application/json",
      authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(params),
  }).then((response) => response.json());
};
```
  
  

### Environment

* GraphiQL Version: 3.0.3
* OS: MacOS Monterey 12.6.3
* Browser: Chrome
* Bundler: next.js
* `react` Version: 18.2.0
* `graphql` Version: 16.7.1

**Comment by acao** [comment] 2023-07-20 14:09
real quick, is this the same as #3307 ? or slightly different?

see comments for the likely source of the regression

**Comment by acao** [comment] 2023-07-23 08:59
closing as a duplicate of #3307

**Closed** 2023-07-23 08:59 UTC
Labels: bug, graphiql
