### ISSUE TITLE
codemirror-graphql esm imports not consistent

### ISSUE THREAD

**Issue by dancarlocanlas** [graphql/graphiql#1643] opened 2020-08-13 03:16 UTC
I noticed that within the es module files (i.e. info.esm.js), they're importing the non-es module version of the utils -- causing import errors:

**Expected**:
info.esm.js:
```js
import { getArgumentReference, getDirectiveReference, getEnumValueReference, getFieldReference, getTypeReference } from './utils/SchemaReference.esm';
```

**Actual**
info.esm.js:
```js
import { getArgumentReference, getDirectiveReference, getEnumValueReference, getFieldReference, getTypeReference } from './utils/SchemaReference';
```

**Comment by amanprateek123** [comment] 2020-09-05 07:19
@dancarlocanlas  I want to contribute in this issue.Please assign this issue to me. Since , i am new to this repo, please guide me  through.

**Comment by acao** [comment] 2020-09-06 03:42
@amanprateek123 your help would be great! no need for assignment, feel free to work on it!

the first thing that comes to mind is that possibly the utils module build was not exported on this build, so you can check unpkg or the installed package to see whether utils includes the esm/ build, whether modules key is in package.json and pathed correctly

sorry i didnt see this earlier, been mostly focused on the lsp and vscode extension, then on vacation.

**Comment by amanprateek123** [comment] 2020-09-06 07:30
Thanks @acao. I'll start working on the issue. I'll get familiar with the codebase and then check the path of utils as mentioned in the issue. I'll get back to you soon.

**Comment by amanprateek123** [comment] 2020-09-06 10:49
@acao I cloned the repo and get familiar with the code. But I didn't see any import error in the console as mentioned in the issue.Please tell me how can I detect this error?

**Comment by acao** [comment] 2020-09-06 14:53
@dancarlocanlas  can you give us more information about how you encountered this error? what module bundler are you using?

when i use webpack or rollup on these packages, as the user above was able to do, they have their own heuristics to resolve the .esm.js or .js files. we've never had to point to specific extensions like that. is there a tool you are using that requires that?

**Comment by acao** [comment] 2020-09-09 14:32
@dancarlocanlas without further information, we won't be able to reproduce this issue, and I will close it soon

**Comment by amanprateek123** [comment] 2020-09-09 15:23
@acao I am also waiting for his reply to work further on this issue.

**Comment by acao** [comment] 2020-09-18 17:13
marking this as a `wontfix`, as webpack, rollup, parcel and other bundlers do not have this issue.

**Comment by dancarlocanlas** [comment] 2020-09-23 11:43
My apologies, was busy the past few weeks 😅

In this case, we were using LItElement along with some of the tools from open-wc, mainly its [es-dev-server](https://github.com/open-wc/open-wc/tree/master/packages/es-dev-server) for the dev server, as well as in storybook and karma testing configurations.

@acao No worries -- for the meantime, the team reverted to using webpack for both the dev and testing servers. And as you've mentioned, since it's not being replicated when using other bundlers -- it might need further checking from the bundling mechanism side of the dev server that we used.

**Comment by lastmjs** [comment] 2021-04-09 23:35
Hey, I'm running into an issue I believe with the `esm` portion of `graphiql`. I'm using `Snowpack`, and I am getting errors in the browser saying that `require` is not defined. Indeed, if I go to `node_modules/graphiql/esm/components/QueryEditor.js` or other similar files, there are lots of requires. Why are these files in the `esm` directory not fully `esm` files?

**Comment by lastmjs** [comment] 2021-05-20 16:44
Could we reopen this issue? I am using Snowpack, and this is causing me problems

**Comment by nowyDEV** [comment] 2021-12-13 11:04
In case someone encounters this issue while using `Vite` setting proper config option should help:

**vite.config.ts**
```typescript
  build: {
      commonjsOptions: {
        transformMixedEsModules: true,
      },
  },
```

**Comment by acao** [comment] 2021-12-13 12:04
I plan on moving to vite/or esbuild for all library bundling soon, instead of just using tsc directly. It should make it easier to support these patterns.

We may keep the typescript project references to keep our monorepo-wide build watch & type check.

I have gotten graphiql working with a generic vite config, the demo should work now.

Not sure how this import pattern leads to inconsistency, because the esm directory contains *only* esm imports. So adding the .esm to import paths seems redundant? But if that’s what bundlers want they can have it 🤷🏻‍♀️

**Comment by acao** [comment] 2021-12-13 12:08
Ohh i see this is a duplicate, and people are mistaking the bundler output as the problem.

 So, no one has gotten a dynamic import for `graphiql`s editor components working. They still do an inline require of the codemirror modules for SSR support as they have since I initially took over the project. I think we need to use `React.lazy`

**Comment by acao** [comment] 2021-12-13 12:09
Duplicate of #1606

**Closed by acao** 2021-12-13 12:09 UTC
Labels: wontfix
