### ISSUE TITLE
Add ruby autocompletion to graphql-language-service-cli

### ISSUE THREAD

**Issue by anark** [graphql/graphiql#1826] opened 2021-04-04 15:28 UTC
For ruby applications that consume graphql apis it would be awesome if the graphql-language-service-cli supported using it via ruby.  Currently this is available for vscode via the graphql-for-vscode(https://marketplace.visualstudio.com/items?itemName=kumar-harsh.graphql-for-vscode) via the tag start and end tags of 
```
<<-GRAPHQL
  query {
   posts{
      title
    }
  }
GRAPHQL
```

It would be great if there was a way to support this via the graphql-language-service-cli as well

**Comment by acao** [comment] 2021-04-04 19:14
Awesome! Agreed! This is a dupe of #1679. Sorry need to clean up issues

This is slated for the next major version of the language server and thus for CLI, vscode-graphql, nvim coc, and all it’s many dependents.

That said, it’s a long way off as this is all volunteer work, so no timelines unfortunately

**Closed by acao** 2021-04-04 19:14 UTC
