### ISSUE TITLE
Subscription operationName not sent

### ISSUE THREAD

**Issue by codepunkt** [graphql/graphiql#605] opened 2017-09-26 08:22 UTC
When having multiple named subscriptions and sending one of them, the operationName is not sent with the query string.

![subscription_operationname](https://user-images.githubusercontent.com/603683/30849912-2db7b5bc-a2a4-11e7-92d1-82792220464c.PNG)

The error message is not shown correctly (see #604). Looking at the console, the operationName is not sent via websocket connection:

![namedsubscriptionstart](https://user-images.githubusercontent.com/603683/30850019-72951b0c-a2a4-11e7-84f4-f466f7bebcd5.PNG)

Therefore, the subscription errors with "Must provide operation name if query contains multiple operations."

**Comment by andrew-w-ross** [comment] 2018-02-20 08:00
Is there any update on this?

**Comment by acao** [comment] 2019-06-25 02:34
@andrew-w-ross new maintainer team here! thanks for the solid bug report. I will get set up to work on this.

**Comment by benjie** [comment] 2019-08-13 09:51
@acao Did you have any luck looking at this?

**Comment by acao** [comment] 2020-05-31 07:00
@benjie i was able to reproduce this i thought? i feel like maybe we fixed it and this was a dupe. let me check

**Comment by acao** [comment] 2020-05-31 07:01
resolved by #664

**Comment by acao** [comment] 2020-05-31 07:02
resolved by #664

**Closed** 2020-05-31 07:01 UTC
Labels: bug, good first issue, help wanted, version 0
