### ISSUE TITLE
monaco-graphql: work with multiple instances?

### ISSUE THREAD

**Issue by jensneuse** [graphql/graphiql#1707] opened 2020-11-02 08:43 UTC
Looking at the monaco-graphql API I was wondering if it's possible to use it for individual instances?
Let's have a look at this example:

```javascript
import { api as GraphQLAPI } from 'monaco-graphql';
GraphQLAPI.setSchema(`
type Query {
    foo: String
}
`);
```

Assuming I have two instances of monaco editor running, how can I set a different schema or settings in general for individual instances?

**Comment by acao** [comment] 2020-11-02 13:27
this mode is designed to be run with as many instances of monaco editor as you like, but currently the language worker only supports one schema at a time.

**Comment by jensneuse** [comment] 2020-11-05 09:35
Would you be interested to make the API multi editor compatible? I'd be happy to help if you give me some pointers. Before working on this we should have a discussion around the API though.

**Comment by acao** [comment] 2020-11-05 12:53
well, it is multi editor compatible! i’ve been able to implement multiple editor instances just fine using this mode. for example, a schema editor and operation editor side by side has worked for me. another example is graphql-code-generator site where they have a PR to introduce this mode with multiple editors.

you may be thinking of multiple schemas maybe? we are far off from needing to support multiple schemas. most graphql projects involve a single schema or a single endpoint to access a federated schema. we have much more important features to support first if that’s the goal

**Comment by acao** [comment] 2020-11-14 13:59
@jensneuse you can do `editor.create(id, { language: 'graphqlDev'})` as much as you like, and create many monaco editor instances.

then, if you want users to be able to switch schemas, that can happen dynamically using `setSchema()` or `setSchemaURI()`. so you could have a dropdown for switching schemas like in our example here in this repo. or you could have each tab of your editor associated with a different schema URL via a sidebar configuration, and then call `setSchema(schemaUrl)` dynamically when mounting that tab.

eventually down the line, we may want to be able to model vscode-graphql and have a multi-project, multi-schema configuration where a file's URI determines which schema it can access. however, most graphql projects only consume one schema at a time, and there are many many ways to allow users to switch schemas with the current mode.

**Comment by Nishchit14** [comment] 2021-09-23 16:58
> so you could have a dropdown for switching schemas like in our example here in this repo

@acao Would you mind sharing the URL for this repo? I couldn't find it.

**Comment by acao** [comment] 2021-09-23 17:15
I got rid of that example because it was annoying to implement in a simple vanilla js example. ended up doubling the size of the monaco webpack example :(

I'm pretty sure `setSchema({ url: "" })` was working, but `setSchemaUrl("")` may have had a bug

**Comment by Nishchit14** [comment] 2021-09-23 18:05
Okay, I have tried to set `.setSchema()`, `.setSchemaUrl()` and `.setSchemaConfig({url: ""})`. The auto-completion feature is not working fine with any of these APIs for multiple schemas. also when the schema is not set then auto-completion shows random values based on previous texts of the edito.

I'll again try with a dedicated example to make sure where the issue is.

**Comment by acao** [comment] 2021-09-23 18:14
do you see the appropriate schema requests happening in the network tab?

**Comment by acao** [comment] 2021-11-16 16:53
@Nishchit14 I am addressing these issues in the in flight PR! sorry I closed this before. you will be able to pass `GraphQLSchema`, request a remote schema, pass AST or introspection JSON or schema SDL, what have you. totally have re-architected the mode. it needs more fine tuning and refactoring but this PR should be ready in a couple of weeks. would love it if you could give the canary release a review!

**Comment by jensneuse** [comment] 2021-11-16 17:39
Yery very nice!

**Comment by acao** [comment] 2021-11-16 17:43
I'm also circling back to an idea one of you originally suggested last year even - monaco-graphql really doesn't need to worry about schema requests. it should expect the user to provide the schema synchronously, and just as schema primitive at the very least, maybe that and introspection JSON. 

the other formats are convenient for passing off to the webworker, but really we should just follow codemirror-graphql here and expect the user to fetch and provide the GraphQLSchema perhaps?

**Comment by acao** [comment] 2021-11-16 19:36
I originally wanted to follow monaco-json's model of supporting the schema requests, but their language service actually has a lot of complexity in how it handles schemas:
https://github.com/microsoft/vscode-json-languageservice/blob/main/src/services/jsonSchemaService.ts

I'm not sure what the best route is to take for graphql. I would like to keep a schema cache, that way we can store information about the schemas every time they change. I think there's a route to even using graphql-config in the browser if we allow users to override the default loaders with just the url loader.

But at the same time, in graphql userland, for something like this, often people will want to provide their schemas in their own ways, and we can just add the simple behaviour of reloading the language features and workers when the schema changes, and focus on other things than managing schemas. What do we think?

**Comment by jensneuse** [comment] 2021-11-16 19:44
It makes total sense to me! I think, the user should fetch the schema the way they want and provide it as a static string. Makes the lifecycle of the worker a lot easier.

**Comment by acao** [comment] 2021-11-22 08:39
#1997 now allows multiple schemas at once, and allows you to specify a `fileMatch` ala monaco-json

**Closed** 2022-11-13 12:21 UTC
Labels: monaco-graphql
