### ISSUE TITLE
[graphiql] <Playground always stick with hint block>

### ISSUE THREAD

**Issue by kaiwenxiao** [graphql/graphiql#3777] opened 2024-09-12 13:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/user-attachments/assets/04fd97a3-9f9d-4712-a4f3-338d880e4648)
You can see the official web. Everytime there are prompt occurs it's never erase, and block the view.
same thing happend when I use with nestjs.
![image](https://github.com/user-attachments/assets/ae7b6ba7-f256-4a06-9b77-7c5921a6bae2)

### Environment

* GraphiQL Version:
* OS:
* Browser:
* Bundler:
* `react` Version:
* `graphql` Version:

**Comment by acao** [comment] 2024-09-12 15:41
this is a duplicate of an issue already reported in codemirror-graphql

**Closed** 2024-09-12 15:42 UTC
Labels: bug, graphiql

**Comment by TallTed** [comment] 2024-09-12 17:43
@acao — I strongly advise always linking to them when citing such [existing issues](https://github.com/graphql/graphiql/issues/3777#issuecomment-2346641291).
