### ISSUE TITLE
[vscode-graphql-syntax] Syntax Highlight breaks if you add a comment/description to a type

### ISSUE THREAD

**Issue by Bas950** [graphql/graphiql#3528] opened 2024-02-02 09:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As you can see the syntax highlight in the attached image breaks as soon as it reaches a comment/description on a type.
![image](https://github.com/graphql/graphiql/assets/34792838/30e15220-fa09-4219-bf65-aa97c8bf03cf)

### Expected Behavior

Syntax highlighting not to break

### Steps To Reproduce

1. add a comment/description to a type

### Environment

* GraphQL: Syntax Highlighting Version: 1.3.1
* GraphQL: Language Feature Support Version: 0.9.1

**Comment by acao** [comment] 2024-02-03 23:54
closing as a duplicate of #3515

**Closed by acao** 2024-02-03 23:54 UTC
Labels: bug, graphiql
