### ISSUE TITLE
publish 0.13.1 to npm and CDNJS

### ISSUE THREAD

**Issue by dulmandakh** [graphql/graphiql#833] opened 2019-05-20 10:03 UTC
I find that 0.13.1 was released several days ago, but npm and cdnjs still don't have this version. Please publish 0.13.1 to NPM and cdnjs.

Thank you

**Comment by benjie** [comment] 2019-05-20 10:12
This is a duplicate of #793; please bear with us whilst we're transferring ownership of the project from Facebook to the GraphQL Foundation — we don't currently have access to the ability to publish.

**Closed by benjie** 2019-05-20 10:12 UTC
Labels: duplicate
