### ISSUE TITLE
DocExplorer a Plugin for GraphiQL 2.0.0

### ISSUE THREAD

**Issue by helloanoop** [graphql/graphiql#1689] opened 2020-10-02 18:46 UTC
Hello,

Is there a plan to make the DocExplorer into a plugin as a part of GraphiQL 2.0.0 ?
If it is, then I am willing to put in the effort to build the plugin (if it is not done yet).

**Comment by cshaver** [comment] 2022-12-08 23:32
duplicate of #2327

**Closed by cshaver** 2022-12-08 23:32 UTC
Labels: enhancement, graphiql
