### ISSUE TITLE
query-editor loads as collapsed

### ISSUE THREAD

**Issue by mattkrick** [graphql/graphiql#170] opened 2016-09-22 15:09 UTC
In my deployment, I've noticed 3 things that can cause the query-editor to load in a collapsed state (`height: 0` no gutters, no line numbers, `left` values that are very large for many child DOM elements). It ends up looking like this: 
![screen shot 2016-09-22 at 7 55 42 am](https://cloud.githubusercontent.com/assets/5514175/18753529/78cba04a-809a-11e6-91f3-17177db4fbb3.png)

I'm current at 0.7.3, and doing any of the 3 causes this bug:
- wrapping the `GraphiQL` component in a div
- loading the css file at the component level (eg using react-helmet)
- upgrading from 0.7.3 to 0.7.8

Has anyone else experienced this? Resizing the window does not help. Additionally calling `cm.refresh()` doesn't help either. `cm.setSize(null, 100)`, which sets the height to 100px, doesn't increase the size of the parent div, so the text sits on top of the variable-editor text. Not sure what else to try. I don't think this is a code mirror issue because the variable-editor loads perfectly fine.
Hopefully whatever result comes out of #152 will also fix this.

**Comment by asiandrummer** [comment] 2016-09-28 05:23
Hey @mattkrick - sorry that you're having a rendering issue. I'm not sure what the actual cause for your problem is yet, but the face that upgrading GraphiQL breaks your app definitely sounds weird. How are you instantiating GraphiQL in your app?

**Comment by mattkrick** [comment] 2016-09-28 14:35
GraphiQL is part of a SPA & is loaded async via webpack + react-router: https://github.com/ParabolInc/action/blob/master/src/universal/modules/admin/containers/Graphql/Graphql.js

The code above is how I'd like it to work, but no luck 😕 . I think the cause is something along the lines of it needing the css to load the initial size & then javascript recalculates the correct size from there. Interesting to note that the variable-editor is collapsed, too, unless you preload data into the localStorage.

For a no-install reproduction you can check it out on the staging server:
1. goto https://action-staging.parabol.co/
2. Login as `graphql@prbl.co` password: `123123`
3. goto https://action-staging.parabol.co/graphql

Cloning the repo works too, just use the same login credentials (or disable line 44 of Graphql.js to bypass auth).

If there's anything else I can do (provide a diff of the working HTML vs non-working HTML, make a branch of the older version where it works, etc) just let me know!

**Comment by bjeld** [comment] 2016-10-12 11:22
Have the same issue here.
I made a quick fix by setting a height on the query editor:
in graphiql.css 

.graphiql-container .query-editor {
  -webkit-flex: 1;
          flex: 1;
  position: relative;
  height: 300px;
}

**Comment by mattkrick** [comment] 2016-10-12 14:56
@bjeld great find!
can confirm that this works for me as long as the stylesheet is _not_ loaded via Helmet.
However, I'm assuming that if it's loaded within javascript, the codemirror JS starts running before the css gets loaded & while the height is good, there is no code inside those windows.

Here's a diff: https://www.diffchecker.com/2m0mYDDR

**Comment by asiandrummer** [comment] 2016-10-13 19:46
@mattkrick - sorry for some delay in investigating this. Like you mentioned it seems like the problem is Helmet doesn't provide `graphiql.css` file at the time when `GraphiQL` component gets mounted for the first time. I cloned `action` repository and played with it a bit, and I think the only solution that I can think of now would be catching when the `graphiql.css` is loaded, and either mount `GraphiQL` component then and/or call CodeMirror's `refresh()` function. I'm guessing that calling `cm.refresh()` didn't work for you because at that time `graphiql.css` wasn't loaded yet.

Or we could do something similar to the below, where we listen to the `load` event of `<link />` we're adding:

(I'm not entirely sure how `react-helmet` operates, but from what I've seen there wasn't an easy way to determine when your `link` tag completes loading, but I think you get the point.)

```js
// In your `export default class Graphiql extends Component {`
constructor() {
  super();
  this.state = { cssLoaded: false };
}

componentDidMount() {
  const $linkEl = document.createElement('link');
  $linkEl.setAttribute('rel', 'stylesheet');
  $linkEl.setAttribute('type', 'text/css');
  $linkEl.setAttribute('href', '/static/css/graphiql.css');

  const eventListener = () =>
    this.setState({ cssLoaded: true }, {
      $linkEl.removeEventListener(eventListener);
    });
  $linkEl.addEventListener('load', eventListener);

  document.head.appendChild($linkEl);
}

render() {
  // ...
  { this.state.cssLoaded ? <GraphiQL fetcher={fetcher} /> : null }
}
```
Note that the above code isn't all-browser-compatible.

**Comment by mattkrick** [comment] 2016-10-13 19:54
Thanks for the investigation!
Strangely enough, code mirror has a window.resize listener but resizing the
window doesn't fix the problem... I think you're right that I should load
it async... Probably set the parent component loaded state to false, then
when the CSS loads, set the state to true in the callback. It's super
dirty, but it seems like the best bet without making a PR to code mirror

**Comment by asiandrummer** [comment] 2016-11-06 21:00
@mattkrick as this issue might be outside of GraphiQL's scope, I'm going to close this issue for now - let me know if you think otherwise!

**Closed by asiandrummer** 2016-11-06 21:00 UTC

**Comment by therockstorm** [comment] 2016-12-28 03:51
For others with this issue, setting your styles to that of the [example](https://github.com/graphql/graphiql/blob/master/example/index.html) fixes the issue.

**Comment by zmb3** [comment] 2017-03-09 20:49
I'm also running into this issue.  I'm a novice when it comes to web development, but I don't see how this is outside of GraphiQL's scope.  Does everyone who wants to use GraphiQL have to manually add their own CSS to get it to render properly?

**Comment by dpikt** [comment] 2017-06-30 14:32
Alternatively, using inline styles:
```jsx
function Explorer () {
  return (
    <div style={{ height: '100vh' }}>
      <GraphiQL fetcher={ fetcher } />
    </div>
  )
}
```
